# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  version: '0.1.1'

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: PowerShell@2
  displayName: 'Remove Vsix project from solution'
  inputs:
    targetType: 'inline'
    script: 'dotnet sln IntelliTectAnalyzer.sln remove IntelliTectAnalyzer\IntelliTectAnalyzer.Vsix\IntelliTectAnalyzer.Vsix.csproj'
    pwsh: true
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '**/*.sln'
    clean: true
    configuration: $(BuildConfiguration)
    msbuildArgs: '/p:Version=$(version)'
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/IntelliTectAnalyzer.Tests.csproj'
- task: PowerShell@2
  displayName: 'dotnet pack'
  inputs:
    targetType: 'inline'
    script: dotnet pack -p:Version="$(version)-ci-$(Build.BuildId)" -o $(Build.ArtifactStagingDirectory)
    pwsh: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'